language: android
sudo: false
jdk:
  - oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-26.0.2
        - android-26
        - extra-android-m2repository
script:
    - cd BlinkInputSample
    - ./gradlew clean :BlinkInputDetectorSample:assembleRelease
    - ./gradlew clean :BlinkInputDirectAPISample:assembleRelease
    - ./gradlew clean :BlinkInputFieldByFieldSample:assembleRelease
    - ./gradlew clean :BlinkInputFieldByFieldSample:assembleRelease
    - ./gradlew clean :BlinkInputTemplatingSample:assembleRelease