language: android
sudo: false
jdk:
  - oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-28.0.3
        - android-28
        - extra-android-m2repository
script:
    - cd BlinkInputSample
    - ./gradlew clean :BlinkInputDetectorSample:assembleRelease
    - ./gradlew clean :BlinkInputDirectAPISample:assembleRelease
    - ./gradlew clean :BlinkInputFieldByFieldSample:assembleRelease
    - ./gradlew clean :BlinkInputRawOcrSample:assembleRelease
    - ./gradlew clean :BlinkInputTemplatingSample:assembleRelease